apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{.Values.ingress.tls_cert_resolver}}
  name: {{.Release.Name}}-ingress
spec:
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - backend:
              service:
                name: {{.Release.Name}}
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: {{.Release.Name}}-tls
