apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secrets
data:
  TLS_DOMAIN: "" # must be left empty to disable ssl cert generation
  SECRET_KEY_BASE: {{.Values.telebugs.env.secret_key_base|b64enc}}
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: {{.Values.telebugs.env.active_record_encryption_primary_key|b64enc}}
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: {{.Values.telebugs.env.active_record_encryption_deterministic_key|b64enc}}
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: {{.Values.telebugs.env.active_record_encryption_key_derivation_salt|b64enc}}
